apiVersion: v1
data:
  mapRoles: |
    - rolearn: arn:aws:iam::695057736078:role/node_group_role
      groups:
      - system:bootstrappers
      - system:nodes
      username: system:node:{{EC2PrivateDNSName}}

    - rolearn: arn:aws:iam::695057736078:role/JenkinsEKSRole
      username: jenkins
      groups:
      - system:masters
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system